spring:
  # 在使用 cloud security 和 cloud oauth2 的情况下使用j2cache，需要额外在 spring redis中加上配置，否则会出现连接失败，原因未知
  redis:
    host: ${redis.host}
    port: ${redis.port}
    database: ${redis.database}
    password: ${redis.password}
  cache:
    type: GENERIC
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/g_take_out?serverTimezone=UTC
    username: ${mysql.username}
    password: ${mysql.password}
  session: ${session}

j2cache: ${j2cache}

lettuce: ${lettuce}

caffeine: ${caffeine}

wechat:
  appid: xxx
  secret: xxx