spring:
  # cache:
  #   type: GENERIC
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/g_take_out?serverTimezone=UTC
    username: ${mysql.username}
    password: ${mysql.password}
  # session: ${session}
  security:
    oauth2:
      ignoreUrls:
        - /addressBook/test2/**
        - /user/userDetails/**
        - /pv/**

j2cache: ${j2cache}

caffeine: ${caffeine}

lettuce: ${lettuce}

security: enable