redis:
  host: xxxx
  port: xxxx
  password: 
  database: 0
  
mysql:
  host: localhost
  port: xxxx
  username: root
  password: xxxx

j2cache:
  open-spring-cache: true
  cache-clean-mode: passive
  allow-null-values: true
  redis-client: lettuce

  l2-cache-open: true
  #以下来自j2cache.properties

  broadcast: lettuce
  L1:
    provider_class: caffeine
  L2:
    provider_class: lettuce
    config_section: lettuce
  sync_ttl_to_redis: true
  default_cache_null_object: false
  serialization: fst
caffeine:
  properties: /caffeine.properties
lettuce:
  mode: single
  namespace:
  storage: generic
  channel: j2cache
  scheme: redis
  hosts: ${redis.host}:${redis.port}
  password: ${redis.password}
  database: ${redis.database}
  sentinelMasterId:
  maxTotal: 100
  maxIdle: 10
  minIdle: 10
  timeout: 10000

session:
  store-type: redis
  #用于存储会话的键的命名空间
  redis:
    namespace: spring：session
  timeout: 30m

jwkSetUri: ${JWK_SET_URI:http://localhost:10020/pb/.well-known/openid-configuration/jwks.json}

secret: ${SECRET:secret}

token:
  accessTokenValiditySeconds: 7200
  refreshTokenValiditySeconds: 259200

# Knife4j的认证路径
knife4j:
  password_token_url: http://localhost:9999/youlai-auth/oauth/token
  
logging:
  level:
    com.alibaba.nacos: warn